### PR TITLE
Removed useless or statements

### PR DESCRIPTION
**Pull request by gt-c**

### CODE REVIEW

**Comment by MicroDroid** [comment]
- Use `something ?` instead of `something !== '' ?` as it could sometimes be null or undefined instead of just empty string. **Except for booleans of course.**
- Squash commits

**Comment by gt-c** [comment]
I tried to make a commit using or statements, which do just that, but they insisted ternaries were faster, and didn’t want that effect.

**Comment by MicroDroid** [comment]
@gt-c who on earth cares whether ternaries are faster. Hello, we're in 2018 where we use Electron for almost anything. Please fix that and I'll check out the previous PR again.

**Comment by MicroDroid** [comment]
Okay, apparently I can't reopen the previous PR because it's coming from the same branch. Please add the readability improvements you previously made here and I'll merge.

**Comment by gt-c** [comment]
@MicroDroid apparently @Thewsomeguy must not be on earth because he cares 👀

**Comment by gt-c** [comment]
all right I will reopen

**Comment by Thewsomeguy** [comment]
I never said I care, I closed the issue on the behalf of @wr1ght. 

image

**Comment by MicroDroid** [comment]
@gt-c Unless I am mistaken, you can't reopen that old pull request. You can only push to this one. Either way, thanks a lot for your contributions. :heart:

**Comment by gt-c** [comment]
@MicroDroid, I recreated the pull request. https://github.com/discordbots/botlister/pull/7

**Pull request closed without merging**
